version: '3.9'

services:
  postgres:
    image: postgres:16   # ใช้เวอร์ชันล่าสุดหรือที่คุณต้องการ
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: accountdb
    ports:
      - "5432:5432"   # map port ให้ host ใช้
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
